### ISSUE TITLE
MarkLogAspect中的切点定义，为何用的是EnableMarkLog注解，而不是MarkLog注解？

### ISSUE THREAD

**Issue by yangziwen** [dadiyang/autologging#10]
你好，最近在学习你写的日志框架，感觉颇有收获。这里有个小疑问想请教下。

在[MarkLogAspect](https://github.com/dadiyang/autologging/blob/master/autologging-aop/src/main/java/com/github/dadiyang/autologging/aop/aspect/MarkLogAspect.java)中定义的切点，为何是基于EnableMarkLog注解(@within(EnableMarkLog) || @annotation(EnableMarkLog))，而不是基于MarkLog注解的呢(@within(MarkLog) || @annotation(MarkLog))？

按我理解，EnableMarkLog注解应该只是用来import诸如AutoLogConfig、MarkLogAspect等相关bean。实际在标注需要打日志的类或者方法时，应该使用MarkLog注解吧。

**Comment by dadiyang** [comment]
嗯，这个应该是个bug

**Comment by dadiyang** [comment]
有兴趣一起共建吗？可以提交一下PR哦

**Comment by yangziwen** [comment]
提交了一个pr，辛苦看下哈
