### ISSUE TITLE
继承父类中的方法调用日志如何打出来

### ISSUE THREAD

**Issue by fdProgrammer** [dadiyang/autologging#13]
1、controller里面调用service -->mapper 想把mapper 里面日志打出来
2.  carService 调用carBiz  carBiz继承一个通用增删改查

@RestController
@RequestMapping("car/")
public class CarController extends BaseController<CarBiz, Car, Integer> {

    @Autowired
    CarService carService;

    @RequestMapping(value = "/aadd1", method = RequestMethod.GET)
    @ResponseBody
    @ApiOperation("新增单个对象")
    public ObjectRestResponse<Car> add1() {
        carService.insertByRandom();
        return null;
    }

    @RequestMapping(value = "/addDefault", method = RequestMethod.GET)
    @ResponseBody
    @ApiOperation("新增单个对象")
    public ObjectRestResponse<Car> addDefault() {
        carService.insertByRandomDefault();
        return null;
    }

}

@Service
public class CarService {

    @Autowired
    CarBiz carBiz;

    @TargetDataSource(dataSourceKey = DataSourceKey.DB_SLAVE1)
    public void insertByRandom() {

        Car car = new Car();
        car.setName("ifaofa");
        car.setId(11111111);
        carBiz.insertSelective(car);

    }

    public void insertByRandomDefault() {

        Car car = new Car();
        car.setName("ifaofa"+ new Random().nextInt(1000));
        carBiz.insertSelective(car);

    }

}

@Service
public class CarBiz extends BusinessBiz<CarMapper, Car> {
}

/**
 * 基础业务类
 * @author woozoom
 * @version 2018/1/13.
 */
public abstract class BusinessBiz<M extends CommonMapper<T>, T>  extends BaseBiz<M, T>  {
    @Override
    public void insertSelective(T entity) {
        EntityUtils.setCreatAndUpdatInfo(entity);
        super.insertSelective(entity);
    }

    @Override
    public void updateById(T entity) {
        EntityUtils.setUpdatedInfo(entity);
        super.updateById(entity);
    }

    @Override
    public void updateSelectiveById(T entity) {
        EntityUtils.setUpdatedInfo(entity);
        super.updateSelectiveById(entity);
    }
}

/**
 * 这是需要打日志的mapper，继承了一个通用的增删改查
 */
@MarkLog
public interface CarMapper extends CommonMapper<Car> {
}

import tk.mybatis.mapper.common.Mapper;
import tk.mybatis.mapper.common.ids.SelectByIdsMapper;

/**
 * 这是通用的增删改查类
 */
public interface CommonMapper<T> extends SelectByIdsMapper<T>,Mapper<T> {
}

**Comment by dadiyang** [comment]
Mapper切面的定义有bug，修复后的还没有发布新版。你可以把MapperLogAspect拷贝到你的项目里，并且加上Component注解，以启用Mapper切面。

**Comment by fdProgrammer** [comment]
ok
