### ISSUE TITLE
结合springControllerAdvice traceId如何统一

### ISSUE THREAD

**Issue by ghost** [dadiyang/autologging#19]
hello，请教一下如何可以同时覆盖@Controller 和 @RestControllerAdvice,因为两个方法都在另一个类中，无法覆盖到，导致每次发生错误的时候会在RestControllerAdvice中的方法重新生成traceId

org.springframework.web.servlet.DispatcherServlet#doDispatch 
try{
handle();
}catch(exception e){
...
}
processDispatchResult();

**Comment by dadiyang** [comment]
需要添加新的切面可以自己扩展

> 若需要切入除本项目提供的切面之外的其他切面，可以继承 AbstractCommonLogAspect 类，并实现 pointcut() 方法声明自己的切点

> 可参考 ServiceLogAspect、MapperLogAspect 和 RepositoryLogAspect 的实现

**Comment by ghost** [comment]
目前没有想到什么合适的方式
有一种是将清理threadLocal的工作放在自定义 HandlerInterceptor 的 afterCompletion 中，但是这种会丧失mq回调时threadLocal的清理工作

因为如果我自定义了 @RestControllerAdvice 的注解也没什么用
例如
func(){
   a();  // Controller
   b(); // RestControllerAdvice
}
再执行到b()的时候a方法已经执行结束了，到b就会重新生成了traceId

不知道大佬有没有好的方式可以解决这个问题😂

**Comment by dadiyang** [comment]
我没有完全理解你遇到的问题，可以把问题讲得详细一些吗？最好有些代码实例

**Comment by ghost** [comment]
假设为get请求
org.springframework.web.servlet.DispatcherServlet#doDispatch
function doDispatch(){
    try{
    handle();  // 会执行controller中的方法
    }catch(exception e){
    ...
    }
    processDispatchResult(e); // 如果有异常会执行RestControllerAdvice中对应异常的方法
}

比方说 我们同时定义了这两个切面，那么
1.handle()方法执行，生成traceId,栈深度+1
2.handle()方法结束, 栈深度-1 = 0，清理了traceid,
3.processDispatchResult()方法执行,此时就会重新生成traceId

请问有没有什么方式可以解决这个问题（我能想到的是使用切面包裹住最外面的方法，但是不知道如何实施）

**Comment by dadiyang** [comment]
直接切doDispatch可以解决这个问题吗
