### ISSUE TITLE
序列化复杂对象很容易出错

### ISSUE THREAD

**Issue by fufenghua** [dadiyang/autologging#9]
return fullMsg ? serializer.serialize(objects) : summary(objects, serializeConfig.getArgsMaxLength());

这一行经常在controller调用service的时候报错，一些传递进去的复杂对象序列化不了，不像普通的javabean。

我的项目里面每次进去都是使用的fastjson进行序列化的

我暂时也不知道如何处理这种复杂且多样的情况

**Comment by dadiyang** [comment]
一般项目里不应该有很多不可被序列化的对象，我已经把常见的类型排除掉了的。建议你们最好规范一下。实在不行，只能把默认序列化器改为ToString的实现了

**Comment by fufenghua** [comment]
自己的包基本不会这样，但是依赖了第三方的包，而我又不得不把这个对象当做参数传入service中，虽然报错不影响啥，但是看着不舒服，索性就ignore了。
解决不了问题，只能解决产生问题的方法了  = .=!!!
